server.port: 7005
spring:
  application:
    jpa:
      show-sql: true  
# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.generate-ddl: true
spring.datasource.initialization-mode: always

spring.datasource:
  url: jdbc:mysql://localhost/users
  username: root
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000


---
spring.profiles: docker

server.port: 8080

spring.data.mongodb.host: mysqldb

spring.datasource.url: jdbc:mysql://mysql/users